### PR TITLE
 Update libcdio-paranoia and fix AppStream validation errors

### PR DESCRIPTION
**Pull request by Zishan-Rahman**
Once this gets merged, #38 can be closed.

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
@tim77 Sorry for the ping, but this PR should be good to merge now. #38 can also be closed as this PR supersedes it :+1:

**Comment by tim77** [comment]
@Zishan-Rahman thanks! I've rebased this via #41
Tiny note: it's always preferable to submit appadata patches to [upstream](https://github.com/audacious-media-player/audacious/commits/master/contrib/audacious.appdata.xml) first.

**Comment by Zishan-Rahman** [comment]
> @Zishan-Rahman thanks! I've rebased this via #41 Tiny note: it's always preferable to submit appadata patches to [upstream](https://github.com/audacious-media-player/audacious/commits/master/contrib/audacious.appdata.xml) first.

@tim77 Thanks to you as well for your hard work. I opened [another PR](https://github.com/flathub/org.atheme.audacious/pull/42) just now, to merge #38 with the changes you just made. Once the test build succeeds there, it should hopefully be good to merge and #38 can be closed once it gets merged.

**Pull request closed without merging**
